name: Test textobj-commentblock

on: ['push', 'pull_request']

jobs:
  test:
    name: 'Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        vim_version:
          - 'head'
          - 'v8.2.0000'
          - 'v8.1.0001'
          - 'v8.0.0001'
        platform: ['Linux', 'macOS', 'Windows']

        include:
          - platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - platform: 'macOS'
            os: 'macos-latest'
            download: 'never'
          - platform: 'Windows'
            os: 'windows-latest'
            download: 'always'

      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v1
        with:
          vim_version: ${{ matrix.vim_version }}
          download: ${{ matrix.download }}
      - name: Setup dependencies
        run: |
          git clone --depth 1 --single-branch https://github.com/thinca/vim-themis ~/themis
          git clone --depth 1 --single-branch https://github.com/kana/vim-textobj-user ~/textobj-user
      - name: Display Vim version
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: Carry out tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ~/themis/bin/themis --runtimepath ~/textobj-user
